# -*- coding: utf-8 -*-
"""Stages.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IzcTnfeo4_NY8WifLU9ft6SXCjy42CBW
"""

import numpy as np
import pandas as pd
import io
from google.colab.data_table import DataTable
DataTable.max_columns = 500
import matplotlib.pyplot as plt
from scipy import stats
from google.colab import drive
drive.mount('/content/drive')

path = "/content/drive/MyDrive/STANFORD/stages-dataset-0.3.0.csv"

stages_dataset = pd.read_csv(path)

from google.colab import drive
drive.mount('/content/drive')

stanford_df = stages_dataset.iloc[1350:1882].copy()
len(stanford_df)

stanford_df

minimal = stanford_df.query('phq_1000 == 0.0 or phq_1000 == 1.0 or phq_1000 == 2.0 or phq_1000 == 3.0 or phq_1000 == 4.0')
mild = stanford_df.query('phq_1000 == 5.0 or phq_1000 == 6.0 or phq_1000 == 7.0 or phq_1000 == 8.0 or phq_1000 == 9.0')
Moderate = stanford_df.query('phq_1000 == 10.0 or phq_1000 == 11.0 or phq_1000 == 12.0 or phq_1000 == 13.0 or phq_1000 == 14.0')
Moderately_Severe = stanford_df.query('phq_1000 == 15.0 or phq_1000 == 16.0 or phq_1000 == 17.0 or phq_1000 == 18.0 or phq_1000 == 19.0')
Severe = stanford_df.query('phq_1000 == 20.0 or phq_1000 == 21.0 or phq_1000 == 22.0 or phq_1000 == 23.0 or phq_1000 == 24.0 or phq_1000 == 25.0 or phq_1000 == 26.0 or phq_1000 == 27.0')

Severe

minimal_len = len(minimal)
mild_len = len(mild)
moderate_len = len(Moderate)
moderately_severe_len = len(Moderately_Severe)
severe_len = len(Severe)

import pandas as pd
import matplotlib.pyplot as plt

category_lengths_df = pd.DataFrame({
    'Category': ['Minimal', 'Mild', 'Moderate', 'Moderately Severe', 'Severe'],
    'Length': [minimal_len, mild_len, moderate_len, moderately_severe_len, severe_len]
})

plt.figure(figsize=(8, 6))
bars = plt.bar(category_lengths_df['Category'], category_lengths_df['Length'], color='skyblue')
plt.title('Category Lengths')
plt.xlabel('PHQ')
plt.ylabel('Length')
plt.xticks(rotation=45)
plt.tight_layout()

for bar, value in zip(bars, category_lengths_df['Length']):
    plt.text(bar.get_x() + bar.get_width() / 2, value + 1, str(value), ha='center', va='bottom')

plt.show()

minimal_gad = stanford_df.query('gad_0800 == 0.0 or gad_0800 == 1.0 or gad_0800 == 2.0 or gad_0800 == 3.0 or gad_0800 == 4.0')
mild_gad = stanford_df.query('gad_0800 == 5.0 or gad_0800 == 6.0 or gad_0800 == 7.0 or gad_0800 == 8.0 or gad_0800 == 9.0')
moderate_gad = stanford_df.query('gad_0800 == 10.0 or gad_0800 == 11.0 or gad_0800 == 12.0 or gad_0800 == 13.0 or gad_0800 == 14.0')
severe_gad = stanford_df.query('gad_0800 == 15.0 or gad_0800 == 16.0 or gad_0800 == 17.0 or gad_0800 == 18.0 or gad_0800 == 19.0 or gad_0800 == 20.0 or gad_0800 == 21.0')

minimal_gad_len = len(minimal_gad)
mild_gad_len = len(mild_gad)
moderate_gad_len = len(moderate_gad)
severe_gad_len = len(severe_gad)

print(minimal_gad_len,mild_gad_len,moderate_gad_len,severe_gad_len)

import pandas as pd
import matplotlib.pyplot as plt

category_lengths_gad_df = pd.DataFrame({
    'Category': ['Minimal', 'Mild', 'Moderate', 'Severe'],
    'Length': [minimal_gad_len, mild_gad_len, moderate_gad_len, severe_gad_len]
})

plt.figure(figsize=(8, 6))
bars = plt.bar(category_lengths_gad_df['Category'], category_lengths_gad_df['Length'], color='skyblue')
plt.title('Category Lengths')
plt.xlabel('GAD')
plt.ylabel('Length')
plt.xticks(rotation=45)
plt.tight_layout()

for bar, value in zip(bars, category_lengths_gad_df['Length']):
    plt.text(bar.get_x() + bar.get_width() / 2, value + 1, str(value), ha='center', va='bottom')

plt.show()